# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: IHUMANE DOCS
email: info@connexxiontelecom.com
description: >- # this means to ignore newlines until "baseurl:"
  INTERACTIVE HUMANE is a customizable and comprehensive software that brings organization and effectiveness to the full range of Human Resource functions and responsibilities
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll


aux_links: 
  "Application":
    - "//app.ihumane.net"
  "Visit Site":
    - "//ihumane.net"
aux_link_new_tab: true
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "IHUMANE Documentation <br/>Copyright &copy; 2020 <a href='https://telecom.connexxiongroup.com'>Connexxion Telecom</a>. <br/> <button class='btn js-toggle-dark-mode mt-4'>Dark Mode</button> 
<script>
  const toggleDarkMode = document.querySelector('.js-toggle-dark-mode');

  jtd.addEvent(toggleDarkMode, 'click', function(){
    if (jtd.getTheme() === 'dark') {
      jtd.setTheme('light');
      toggleDarkMode.textContent = 'Dark Mode';
    } else {
      jtd.setTheme('dark');
      toggleDarkMode.textContent = 'Light Mode';
    }
  });
</script> "
search_enabled: true

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
